import { promises as fs } from 'fs';
import path from 'path';
import { AgilePlan, AgilePlanSchema } from './types';

export class AgilePlanner {
    private readonly workspaceRoot: string;
    private readonly planFileName = '.agile_plan.json';

    constructor(workspaceRoot: string = process.cwd()) {
        this.workspaceRoot = workspaceRoot;
    }

    /**
     * Validates and saves an agile plan proposed by the LLM agent.
     * @param rawPayload The raw JSON object generated by the agent.
     * @returns The path to the saved staged plan.
     */
    public async stagePlan(rawPayload: unknown): Promise<{ success: true; filePath: string } | { success: false; errors: string[] }> {
        const validationResult = AgilePlanSchema.safeParse(rawPayload);

        if (!validationResult.success) {
            const errors = validationResult.error.errors.map(err => `${err.path.join('.')}: ${err.message}`);
            return { success: false, errors };
        }

        const planPath = path.join(this.workspaceRoot, this.planFileName);
        
        await fs.writeFile(
            planPath, 
            JSON.stringify(validationResult.data, null, 2), 
            'utf-8'
        );

        return { success: true, filePath: planPath };
    }

    /**
     * Reads the currently staged plan, if any.
     */
    public async getStagedPlan(): Promise<AgilePlan | null> {
        const planPath = path.join(this.workspaceRoot, this.planFileName);
        try {
            const content = await fs.readFile(planPath, 'utf-8');
            return JSON.parse(content) as AgilePlan;
        } catch {
            return null; // File doesn't exist or is unreadable
        }
    }
}
